

<!--<div class="page-header">-->
<!--    <h1>Congratulations!</h1>-->
<!--</div>-->
<!---->
<!--<p>You're now flying with Phalcon. Great things are about to happen!</p>-->
<!---->
<!--<p>This page is located at <code>views/index/index.phtml</code></p>-->

<?php
//javascriptInclude("timeStart.js");

//echo $this->tag->linkTo(
//    'signup',
//    'Sign Up Here'
//);

//echo $this->tag->form("signup/register"); ?>

<!--    <p>-->
<!--        <label for="name">time_start</label>-->
<!--        --><?php //echo $this->tag->textField("name"); ?>
<!--    </p>-->



<!--    <button name="startButton" type="button" onclick="startTime()">start</button>-->
<!--    <div class="txtHint">-->
<!---->
<!--    </div>-->

<!--</form>-->


<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>-->
<!--<script>-->
<!--    function startTime()-->
<!--    {-->
<!--        $.ajax({-->
<!--            url: "test.html",-->
<!--            context: document.body-->
<!--        }).done(function () {-->
<!--            $(this).addClass("done");-->
<!--        });-->
<!--    }-->
<!---->
<!--tracker -->
<!--</script>-->



<?php

//if ($users->count() > 0) {
//    ?>
<!--    <table class="table table-bordered table-hover">-->
<!--        <thead class="thead-light">-->
<!--        <tr>-->
<!--            <th>#</th>-->
<!--            <th>Name</th>-->
<!--            <th>Email</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tfoot>-->
<!--        <tr>-->
<!--            <td colspan="3">Users quantity: --><?php //echo $users->count(); ?><!--</td>-->
<!--        </tr>-->
<!--        </tfoot>-->
<!--        <tbody>-->
<!--        --><?php //foreach ($users as $user) { ?>
<!--            <tr>-->
<!--                <td>--><?php //echo $user->id; ?><!--</td>-->
<!--                <td>--><?php //echo $user->name; ?><!--</td>-->
<!--                <td>--><?php //echo $user->email; ?><!--</td>-->
<!--            </tr>-->
<!--        --><?php //} ?>
<!--        </tbody>-->
<!--    </table>-->
<!--    --><?php
//}
//
//

//print_die($time = Time::find()->toArray());
//?>











