<?php
//echo $this->tag->form("tracker/staff"); ?>






<!--<p>-->
<!--    <label for="name">start</label>-->
<!--    --><?php ////echo $this->tag->textField("name"); ?>
<!--</p>-->
<!---->
<?php $this->assets->outputJs() ?>
    <input id="id" type="hidden" name="id" value="" />
<input id="timerbutton"  class="mk" type="button" name="timerbutton" value="start" />

<table id="timertable">

</table>


<table>
<tr>
    <tn id="start-test"></tn>
</tr>
</table>




